isabelle = User.create(first_name: "Isabelle", last_name: "Pino", username: "isabelle", password: "password1", password_confirmation: "password1")
brian = User.create(first_name: "Brian", last_name: "Kang", username: "brian", password: "password2", password_confirmation: "password2")
bruno = User.create(first_name: "Bruno", last_name: "Gonzalez", username: "bruno", password: "password3", password_confirmation: "password3")
nicole = User.create(first_name: "Nicole", last_name: "Dalcin", username: "nicole", password: "password4", password_confirmation: "password4")


Category.create(name: "Design")
Category.create(name: "Technology")
Category.create(name: "Productivity")
Category.create(name: "Entertainment")
Category.create(name: "Sports")
Category.create(name: "Games")
Category.create(name: "Food")

Project.create(title: "Basketball", description: "A never-before-seen sports endeavor where one must place a leather bouncy ball into a 11-foot basket. Whichever team of 5 players scores more wins", funds_needed: 1000, creator_id: isabelle.id, category_id: 5)
Project.create(title: "Invisibility Cloak", description: "Ever wanted to go off-the-grid or disappear from humanity's watchful eyes? Well, here's your very own invisible cloak. Warning: hand wash only-- do not mix with colors.", funds_needed: 1000000, creator_id: brian.id, category_id: 1)
Project.create(title: "Hoverboard", description: "A board that hovers! Above the ground! Kind of like a skateboard, but without wheels.", funds_needed: 50000, creator_id: isabelle.id, category_id: 2)
Project.create(title: "Underwatch", description: "Multiplayer first-person-shooter game of unlikely heroes, talking animals, and humanoid robots. Click heads to win.", funds_needed: 2000, creator_id: brian.id, category_id: 6)
Project.create(title: "Real Men Cry: A Biography of John Cena", description: "John Cena is the manliest of men who is in tune with his feelings. Support this project to learn how this muscular fellow grew to have a heart even bigger than his biceps.", funds_needed: 100, creator_id: bruno.id, category_id: 4)
Project.create(title: "Sir Acha", description: "A new kind of hot sauce that warms your soul, quite literally. Seriously, it's really spicy. It might make you cry, which John Cena approves.", funds_needed: 2000, creator_id: nicole.id, category_id: 7)
